### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by clewis7** [hantman-lab/animal-soup#1]
- [x] update README
- [x] change ethogram cleaner from using button events to keyboard shortcuts 
- [ ] add labels to ethogram plots for the behaviors
- [x] create tests for CI pipeline
     - [ ] `create_df`, `load_df`
     - [ ] `remove_item`, `add_item`
     - [ ] assert `trial_selector` is correct 
     - [ ] assert `pydatagrid` is correct 
- [ ]  add histogram view for behaviors using EMD
